export const INITIATE_APP = 'INITIATE_APP';
export const INITIATE_APP_DONE = 'INITIATE_APP_DONE';

export const INITIATE_USER = 'INITIATE_USER';
export const INITIATE_USER_DONE = 'INITIATE_USER_DONE';
